name: afc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1h=h7b6447c_0
  - pip=20.2.4=py36h06a4308_0
  - python=3.6.12=hcff3b4d_2
  - readline=8.0=h7b6447c_0
  - setuptools=50.3.1=py36h06a4308_1
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - aiohttp==3.7.2
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - async-timeout==3.0.1
    - attrs==20.3.0
    - backcall==0.2.0
    - beautifulsoup4==4.9.3
    - bleach==3.2.1
    - blessings==1.7
    - cachetools==4.1.1
    - cffi==1.14.3
    - chardet==3.0.4
    - click==7.1.2
    - colorama==0.4.4
    - colorful==0.5.4
    - contextvars==2.4
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - filelock==3.0.12
    - gensim==3.8.3
    - google==3.0.0
    - google-api-core==1.23.0
    - google-auth==1.23.0
    - googleapis-common-protos==1.52.0
    - gpustat==0.6.0
    - grpcio==1.33.2
    - hiredis==1.1.0
    - idna==2.10
    - idna-ssl==1.1.0
    - immutables==0.14
    - importlib-metadata==2.0.0
    - ipykernel==5.3.4
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - jinja2==2.11.2
    - joblib==0.17.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.7
    - jupyter-console==6.2.0
    - jupyter-core==4.6.3
    - jupyterlab-pygments==0.1.2
    - kiwisolver==1.3.1
    - markupsafe==1.1.1
    - matplotlib==3.3.2
    - mistune==0.8.4
    - msgpack==1.0.0
    - multidict==5.0.0
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.2
    - notebook==6.1.5
    - numpy==1.19.4
    - nvidia-ml-py3==7.352.0
    - opencensus==0.7.11
    - opencensus-context==0.1.2
    - packaging==20.4
    - pandas==1.1.4
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==6.2.0
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.8
    - protobuf==3.13.0
    - psutil==5.7.3
    - ptyprocess==0.6.0
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.7.2
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.4
    - pyyaml==5.3.1
    - pyzmq==19.0.2
    - qtconsole==4.7.7
    - qtpy==1.9.0
    - ray==1.0.1
    - redis==3.4.1
    - requests==2.24.0
    - rsa==4.6
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - send2trash==1.5.0
    - six==1.15.0
    - smart-open==3.0.0
    - soupsieve==2.0.1
    - terminado==0.9.1
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - torch==1.2.0
    - torchvision==0.4.0
    - tornado==6.1
    - tqdm==4.51.0
    - traitlets==4.3.3
    - typing-extensions==3.7.4.3
    - urllib3==1.25.11
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - yarl==1.6.2
    - zipp==3.4.0
prefix: /home/NAME/anaconda3/envs/afc

